In [5]:
from tensorflow.keras.preprocessing.text import one_hot


In [6]:
sent=[
    'I love programming in Python',
    'Python is great for data science',
    'Data science is an exciting field',
    'I enjoy learning new programming languages',
    'Machine learning is a subset of data science',
]

In [7]:
sent 
voc_size = 10000

In [8]:
onehotre=[one_hot(words,voc_size) for words in sent]
onehotre

[[1516, 8466, 3404, 2300, 7344],
 [7344, 828, 6334, 8193, 596, 9177],
 [596, 9177, 828, 2813, 242, 1424],
 [1516, 4097, 2777, 7328, 3404, 2989],
 [287, 2777, 828, 2586, 3215, 3929, 596, 9177]]

In [14]:
#word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [15]:
import numpy as np


In [16]:
sent_length = 8 # padding sequences to ensure uniform length
embedded_docs = pad_sequences(onehotre, padding='pre', maxlen=sent_length)   
print(embedded_docs)



[[   0    0    0 1516 8466 3404 2300 7344]
 [   0    0 7344  828 6334 8193  596 9177]
 [   0    0  596 9177  828 2813  242 1424]
 [   0    0 1516 4097 2777 7328 3404 2989]
 [ 287 2777  828 2586 3215 3929  596 9177]]


In [19]:
# feature representation
dim=10 ## dimention of embedding vector
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse') 

# Build the model by running a forward pass (optional, ensures model.summary() works)
model.predict(embedded_docs)

c:\Users\amitk\OneDrive\Desktop\python\vnev\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step


array([[[-3.08143850e-02, -4.79107499e-02,  3.94943096e-02,
         -4.85165045e-03,  8.52383301e-03,  7.11926073e-03,
         -4.51225638e-02, -2.51258966e-02, -2.29800697e-02,
         -3.53219397e-02],
        [-3.08143850e-02, -4.79107499e-02,  3.94943096e-02,
         -4.85165045e-03,  8.52383301e-03,  7.11926073e-03,
         -4.51225638e-02, -2.51258966e-02, -2.29800697e-02,
         -3.53219397e-02],
        [-3.08143850e-02, -4.79107499e-02,  3.94943096e-02,
         -4.85165045e-03,  8.52383301e-03,  7.11926073e-03,
         -4.51225638e-02, -2.51258966e-02, -2.29800697e-02,
         -3.53219397e-02],
        [-4.04948369e-02,  4.18666489e-02,  9.17861611e-03,
          4.14150469e-02, -2.73956303e-02,  2.35891677e-02,
         -3.49016190e-02, -3.76298316e-02,  3.18760611e-02,
         -4.11247723e-02],
        [-3.06556951e-02,  4.10009064e-02, -1.93201900e-02,
         -1.94626451e-02,  1.69193782e-02,  7.49025494e-03,
         -1.73284784e-02,  2.36292928e-03, -2.782127

In [20]:
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (5, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)